# Part A: load Data

In [52]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn

In [53]:
data = pd.read_csv('../data/BTCUSDT.csv', sep='|', nrows=1000, header=None, usecols=[0, 1, 2, 3, 4, 5], names=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
print(data.head())

    timestamp     open     high      low    close    volume
0  1502942400  4261.48  4261.48  4261.48  4261.48  1.775183
1  1502942460  4261.48  4261.48  4261.48  4261.48  0.000000
2  1502942520  4280.56  4280.56  4280.56  4280.56  0.261074
3  1502942580  4261.48  4261.48  4261.48  4261.48  0.012008
4  1502942640  4261.48  4261.48  4261.48  4261.48  0.140796


In [54]:
data['timestamp'] = pd.to_datetime(data['timestamp'], unit='s')
data.set_index('timestamp', inplace=True)
print(data)

                        open     high      low    close    volume
timestamp                                                        
2017-08-17 04:00:00  4261.48  4261.48  4261.48  4261.48  1.775183
2017-08-17 04:01:00  4261.48  4261.48  4261.48  4261.48  0.000000
2017-08-17 04:02:00  4280.56  4280.56  4280.56  4280.56  0.261074
2017-08-17 04:03:00  4261.48  4261.48  4261.48  4261.48  0.012008
2017-08-17 04:04:00  4261.48  4261.48  4261.48  4261.48  0.140796
...                      ...      ...      ...      ...       ...
2017-08-17 20:35:00  4302.96  4302.96  4302.96  4302.96  0.052740
2017-08-17 20:36:00  4302.96  4302.96  4302.96  4302.96  0.585532
2017-08-17 20:37:00  4301.91  4301.91  4301.91  4301.91  0.445848
2017-08-17 20:38:00  4301.91  4301.91  4301.91  4301.91  0.372403
2017-08-17 20:39:00  4301.91  4303.18  4262.53  4303.18  1.161897

[1000 rows x 5 columns]


In [55]:
data_tensor = torch.from_numpy(data.values).to(torch.float32)
print(data_tensor)

tensor([[4.2615e+03, 4.2615e+03, 4.2615e+03, 4.2615e+03, 1.7752e+00],
        [4.2615e+03, 4.2615e+03, 4.2615e+03, 4.2615e+03, 0.0000e+00],
        [4.2806e+03, 4.2806e+03, 4.2806e+03, 4.2806e+03, 2.6107e-01],
        ...,
        [4.3019e+03, 4.3019e+03, 4.3019e+03, 4.3019e+03, 4.4585e-01],
        [4.3019e+03, 4.3019e+03, 4.3019e+03, 4.3019e+03, 3.7240e-01],
        [4.3019e+03, 4.3032e+03, 4.2625e+03, 4.3032e+03, 1.1619e+00]])


In [56]:
data_tensor.dtype, data_tensor.shape, data_tensor.device

(torch.float32, torch.Size([1000, 5]), device(type='cpu'))

# Part B: Computational Graph Internals

In [57]:
x = data_tensor[0].reshape(1, -1)
w = torch.randn_like(x, requires_grad=True)
b = torch.randn(1, requires_grad=True)
x.shape, w.shape, b.shape

(torch.Size([1, 5]), torch.Size([1, 5]), torch.Size([1]))

In [58]:
x, w, b

(tensor([[4.2615e+03, 4.2615e+03, 4.2615e+03, 4.2615e+03, 1.7752e+00]]),
 tensor([[ 0.9872, -1.3224, -0.8460, -0.4908, -0.7180]], requires_grad=True),
 tensor([-0.9272], requires_grad=True))

In [59]:
y = x @ w.T + b
y

tensor([[-7127.2661]], grad_fn=<AddBackward0>)

In [60]:
y.backward()
w.grad, b.grad

(tensor([[4.2615e+03, 4.2615e+03, 4.2615e+03, 4.2615e+03, 1.7752e+00]]),
 tensor([1.]))

In [61]:
x, w, b

(tensor([[4.2615e+03, 4.2615e+03, 4.2615e+03, 4.2615e+03, 1.7752e+00]]),
 tensor([[ 0.9872, -1.3224, -0.8460, -0.4908, -0.7180]], requires_grad=True),
 tensor([-0.9272], requires_grad=True))